name: Continuos Integration

# Trigger the workflow on pushes to the main branch or pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
            fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.10.0  # Change to your node version if needed

      # Step 3: Install dependencies
      - name: Install Deps
        run: npm install

