name: Continuous Deployment

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build the project
        run: npm run build

      # Deploy to GitHub Pages

      - name: Deploy to production url

        if: github.ref == 'refs/heads/main' 

        uses: JamesIves/github-pages-deploy-action@4.1.4 
        with:
          branch: gh-pages # The branch where you want to deploy (GitHub Pages usually uses gh-pages)
          folder: dist 
          clean: true     # The folder where Vite generates the build (for Vite, it's typically 'dist') 

      - name: Deploy to dev url

        if: github.ref == 'refs/heads/development'  

        uses: JamesIves/github-pages-deploy-action@4.1.4

        with:
          branch: dev-gh-pages      # Deploy to a separate branch for development
          folder: dist              # Folder where Vite outputs the build
          clean: true 
